name: test github action

on:
  workflow_call:
    inputs:
      varstr:
        required: true
        type: string

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - run: ip a
      - run: echo ${{ github.env }}
      - run: echo "Hi ${{ env.mascot }}"
      - run: echo "xxxxxxxxx ${{ github.jobs }}"
      - uses: actions/download-artifact@v3
        id: download
        with:
          name: 'my-artifact'
          path: artifacts
      - run: ls -l artifacts
      - run: |
          curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts
      - name: setup tmate session for debugging when event is PR
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 120
